services:
  postgres:
    image: postgres:latest
    ports:
      - 5440:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
#    healthcheck:
#      test: [ "CMD", "pg_isready", "-U", "ferdian" ]
#      interval: 5s
#      timeout: 5s
#      retries: 5

  redis:
      image: redis:7
      ports:
        - "6380:6379"
      command: [ "redis-server" ]
  #    healthcheck:
  #      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
  #      interval: 1s
  #      timeout: 3s
  #      retries: 5

volumes:
  postgres_data:
